config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'dogs#index'
  resources :dogs do
    get :adoption
    put :adoption
    get :confirm_adoption
    put :confirm_adoption
    get :unconfirm_adoption
    put :unconfirm_adoption
  end
  resources :users, only: [:show]

end

app/models/dog.rb
class Dog < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_devise_params, if: :devise_controller?
    
    def configure_devise_params
    	devise_parameter_sanitizer.for(:sign_up) do |u|
        	u.permit(:email, :password, :password_confirmation, :name, :phone)
        end
        devise_parameter_sanitizer.for(:account_update) do |u|
    		u.permit(:email, :password, :password_confirmation, :current_password, 	:name, :address, :phone)
    	end
    end
     
   
     def authorize_owner!
      if (current_user != @dog.user) or (@dog.adopted == 1)
        flash[:alert] = "You don't have the permissions to do this."
        redirect_to root_url
      end
    end

    helper_method :authorize_owner!
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	before_action :set_dog, only: [:show, :edit, :update, :destroy]
	before_action :authorize_owner!, only: [:edit, :update, :destroy]
	before_action :set_dog_for_adoption, only: [:adoption, :confirm_adoption, :unconfirm_adoption]
	
	def index
		@dogs = Dog.where(:adopted => -1).paginate(:page => params[:page], :per_page => 20)
	end
	#Requisition.where(:accepted => false).order(:created_at => 'DESC').paginate(:page => params[:page], :per_page => 10).order(:created_at => 'DESC')

	def show
	end

	def new
		@dog = Dog.new
	end

	def create
		@dog = Dog.new(dog_params)
		@dog.user = current_user
		if @dog.save
			flash[:notice] = "Your dog announcement has been saved correctly."
			redirect_to @dog
		else
			flash[:alert] = "Your dog announcement has not been saved correctly."
			render action: "new"
		end
	end

	def edit
	end

	def update
		if @dog.update(dog_params)
			flash[:notice] = "Your dog announcement has been saved correctly."
			redirect_to @dog
		else
			flash[:alert] = "Your dog announcement has not been saved correctly."
			render action: "edit"
		end
	end

	def destroy
		@dog.destroy
		flash[:notice] = "Your dog announcement has been eliminated."
		redirect_to root_url
	end

	def adoption
		@dog.update_attributes( :adopted => 0 )
		@dog.update_attributes( :adopter_id => current_user.email )
		flash[:notice] = "We send you an email with the contact data of the owner, we also sent an email to the owner with your contact data"
		redirect_to @dog
	end

	def confirm_adoption
		@dog.update_attributes( :adopted => 1 )
		flash[:notice] = "Yes! We are generating the certificate."
		redirect_to @dog

	end

	def unconfirm_adoption
		@dog.update_attributes( :adopted => -1 )
		@dog.update_attributes( :adopter_id => nil )
		flash[:notice] = "Oh no! Don't worry your dog will appear again on the main page, so that someone can adopt it"
		redirect_to @dog
	end

	private
		def dog_params
			params.require(:dog).permit(:name, :description, :color, :gender, :age, :size, :sterilized, :vaccined, :urgent, :city, :state, :country, :photo1, :photo2, :photo3, :specify, :breed, :adopter_requirements)
		end

		def set_dog
			@dog = Dog.find(params[:id])
			rescue  ActiveRecord::RecordNotFound
			flash[:alert] = "This isn't the dog you are looking for."
			redirect_to root_url
		end

		def set_dog_for_adoption
			@dog = Dog.find(params[:dog_id])
			rescue  ActiveRecord::RecordNotFound
			flash[:alert] = "This isn't the dog you are looking for."
			redirect_to root_url
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@dogs = Dog.where(:user => @user).paginate(:page => params[:page], :per_page => 20)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
	<% if @dog.errors.any? %>	
		<h2><%= pluralize(@dog.errors.count, "error") %></h2>
			<ul>
				<% @dog.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
	<% end %>

	<p><%= f.text_field :name, placeholder: "Name" %></p>
	<p><%= f.select(:breed, ['OTHER OR MIX', 'AFFENPINSCHER', 'AFGHAN HOUND','AIREDALE TERRIER', 'AIREDALE TERRIER', 'AKITA', 'ALASKAN MALAMUTE', 'AMERICAN ENGLISH COONHOUND', 'AMERICAN ESKIMO DOG', 'AMERICAN FOXHOUND', 'AMERICAN HAIRLESS TERRIER', 'AMERICAN LEOPARD HOUND', 'AMERICAN STAFFORDSHIRE TERRIER', 'AMERICAN WATER SPANIEL', 'ANATOLIAN SHEPHERD DOG', 'APPENZELLER SENNENHUNDE', 'AUSTRALIAN CATTLE DOG', 'AUSTRALIAN SHEPHERD', 'AUSTRALIAN TERRIER', 'AZAWAKH', 'BARBET', 'BASENJI', 'BASSET FAUVE DE BRETAGNE', 'BASSET HOUND', 'BEAGLE', 'BEARDED COLLIE', 'BEAUCERON', 'BEDLINGTON TERRIER', 'BELGIAN LAEKENOIS', 'BELGIAN MALINOIS', 'BELGIAN SHEEPDOG', 'BELGIAN TERVUREN', 'BERGAMASCO', 'BERGER PICARD', 'BERNESE MOUNTAIN DOG', 'BICHON FRISE', 'BIEWER TERRIER', 'BLACK AND TAN COONHOUND', 'BLACK RUSSIAN TERRIER', 'BLOODHOUND', 'BLUETICK COONHOUND', 'BOERBOEL', 'BOLOGNESE'], {}, :id  => 'breed' ) %></p>
	<div style="visibility: visible;" id="specify">
		<p><%= f.text_field :specify, placeholder: "Specify:" %></p>
	</div>
	<p><%= f.text_area :description, placeholder: "Describe the dog's personality" %></p>
	<p><%= f.text_area :color, placeholder: "Describe the dog's color and fur" %></p>
	<p><%= f.select(:gender, ['Female', 'Male']) %></p>
	<p><%= f.text_field :age, placeholder: "Age" %></p>
	<p><%= f.select(:size, ['Small', 'Medium', 'Large']) %></p>
	<p><%= f.check_box :sterilized %>Is sterilized?</p>
	<p><%= f.check_box :vaccined %>Is vaccined?</p>
	<p><%= f.check_box :urgent, id: "mega_urgent" %>Is urgent?</p>
	<div style="visibility: hidden;" id="dates">
		<p>Adoption needed before: <%= f.date_select :adopt_before %></p>
	</div>

	<p>Photo 1 (This one will be the profile pic) <%= f.file_field :photo1 %></p>
	<p>Photo 2  <%= f.file_field :photo2 %></p>
	<p>Photo 3  <%= f.file_field :photo3 %></p>

	<p><%= f.text_area :adopter_requirements, placeholder: "Describe your dogs special requirements or anythig extra" %></p>
	<p><%= f.text_field :city, placeholder: "Guadalajara" %></p>
	<p><%= f.text_field :state, placeholder: "Jalisco" %></p>
	<p><%= f.text_field :country, placeholder: "Mexico" %></p>

	<p><%= f.submit "Save" %>

<% end %>

<script type="text/javascript">
	//console.log("alñas");
	var check = document.getElementById("mega_urgent");
	check.onchange = function() {
	var h = document.getElementById("dates");
	//console.log("la");
     if(this.checked) {
     	//console.log("lol");
        
        h.style.visibility ="visible"
     } 

    if(this.checked == false) {
     	//console.log("lol");
         
        h.style.visibility ="hidden"
     }
};

$('#breed').on('change', function(event) {
	console.log("lala");
	var action = $(this).val();
	var h = document.getElementById("specify");
	h.style.visibility = "hidden";
	//console.log("lol");
	if (action != "OTHER OR MIX"){
		//console.log("e");
		h.style.visibility = "hidden";
	} else {
		h.style.visibility = "visible";
		//console.log("i");
		
	}

});
</script>

app/views/dogs/edit.html.erb
<h1>Editing <%= @dog.name %></h1>
<%= render "form" %>

app/views/dogs/index.html.erb
<h1>Dogs that need adoption</h1>

<%= link_to "New dog announcement", new_dog_path %>
<% @dogs.each do |dog| %>
	<%= link_to dog do %>
		<%= image_tag dog.photo1 %> | <%= dog.name %> | <%= dog.breed %> | <%= dog.city %> | <%= dog.state %> | <%= dog.country %>
	<% end %>
<% end %>

<%= will_paginate @dogs, :previous_label => 'Previous', :next_label => 'Next'  %>

app/views/dogs/new.html.erb
<h1>New dog announcement</h1>
<%= render "form" %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<p>Owner: <%= link_to @dog.user.name, @dog.user %></p>
<% if @dog.adopted == -1 %>
	<p>Needs adoption <%= link_to "Adopt it now!", dog_adoption_path(@dog) %></p>
<% end %>

<% if @dog.adopted == 0 %>
	<p>In process of adoption</p>
	<!-- This buttons only appear to the user that is the owner of the dog thats why the if-->
	<% if current_user == @dog.user %>
		<p> Have you proceeded with the adoption succesfully? Then confirm it so that we can proceed with the certificate of adoption! Not succesful? Don't worry! Click unconfirm button and your dog will appear again in the system so that other users can adopt it!</p>
		<p><%= link_to "Confim Adoption!", dog_confirm_adoption_path(@dog) %></p>
		<p><%= link_to "Unconfirm Adoption!", dog_unconfirm_adoption_path(@dog) %></p>
	<% end %>
<% end %>

<% if @dog.adopted == 1 %>
	<p>Adopted!</p>
<% end %>

<% if current_user == @dog.user  and @dog.adopted != 1 %>
	<p><%= link_to "Edit", edit_dog_path(@dog) %></p>
	<p><%= link_to "Delete", dog_path(@dog), method: :delete, data: { confirm: "Are you sure?"}  %></p>
<% end %>

<p>Breed: <%= @dog.breed %></p>
<% if !@dog.specify.blank? %>
	<p><%= @dog.specify %></p>
<% end %>
<p>Personality: <%= simple_format(@dog.description) %></p>
<p>Color: <%= simple_format(@dog.color) %></p>
<p>Gender: <%= @dog.gender %></p>
<p>Size: <%= @dog.size %></p>
<p>Age: <%= @dog.age %></p>

<% if @dog.sterilized %>
	<p>Sterilized: Yes</p>
<% else %>
	<p>Sterilized: No</p>
<% end %>
<% if @dog.vaccined %>
	<p>Vaccined: Yes</p>
<% else %>
	<p>Vaccined: No</p>
<% end %>
<% if @dog.urgent %>
	<p>Needed adoption before: <%= @dog.adopt_before %></p>
<% end %>

<p>Special requirements: <%= @dog.adopter_requirements %></p>
<p>City (where the dog is located) <%= @dog.city %></p>
<p>State (where the dog is located)<%= @dog.state %></p>
<p>Country (where the dog is located)<%= @dog.country %></p>

<p>Photo 1 (This is the profile photo): <%= @dog.photo1 %></p>
<p>Photo 2<%= @dog.photo2 %></p>
<p>Photo 3<%= @dog.photo3 %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdoptaUnPerro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |key, value| %>
	    <% if flash %>
	    <div id="alert">
	      <% if notice %>
	        <div id = '<%= key %>'>
	          <%= notice %>
	        </div>
	      <% end %>
	      <% if alert %>
	        <div id = '<%= key %>'>
	          <%= alert %>
	        </div>
	      <% end %>
	    </div>
	    <% end %>
	<% end %>
	<p><%= link_to "Home", root_path %> </p>
	<% if user_signed_in? %>
		<p><%= link_to "Profile", current_user %> <%= link_to "Log Out", destroy_user_session_path %></p>
	<% else %>
		<p><%= link_to "Log In", new_user_session_path %> or <%= link_to "Join", new_user_registration_path %></p>
	<% end %>

	<%= yield %>
	
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if current_user == @user %>
	<p><%= link_to "Edit Profile", edit_registration_path(@user) %></p>
	<p><%= @user.email %></p>
	<p><%= @user.phone %></p>
	<p><%= link_to "Create new dog announcement", new_dog_path %>
	<h3>My announcements</h3>
<% else %>
	<h3>This user announcements</h3>
<% end %>

<% @dogs.each do |dog| %>
	<%= link_to dog do %>
		<p><%= dog.photo1 %> | <%= dog.name %> | <%= dog.breed %> | <%= dog.city %> | <%= dog.state %> | <%= dog.country %>  | <% if dog.adopted == 1 %> Yes! <%= dog.name %> was adopted!<% end %></p>
	<% end %>
<% end %>

<%= will_paginate @dogs, :previous_label => 'Previous', :next_label => 'Next'  %>